#!/usr/bin/env ruby
#^syntax detection
source 'https://api.berkshelf.com'

cookbook 'yum', '~> 3.3.2'
cookbook 'yum-epel', '~> 0.6.2'
cookbook 'yum-ius', '~> 0.4.1'
cookbook 'yum-webtatic', '~> 0.4.0'
cookbook 'mysql', '~> 6.1.2'
cookbook 'php', '~> 1.3.12'
cookbook 'apache2', '~> 3.1.0'
cookbook 'data-bag-merge', '~> 0.2.4'

cookbook 'config-driven-helper', :github => 'ubick/chef-config-driven-helper', :ref => '02490b0cde37d02c412ff44511b33e0f4520a8f2'
cookbook 'php-fpm', :github => 'inviqa/cookbook-php-fpm', :tag => '0.6.11'

cookbook 'lorekeepers', :path => 'site-cookbooks/lorekeepers'
